Asilo5/hate-it-n-rate-it

package-lock.json
package.json
src/Containers/App/App.js
src/Containers/MoviesContainer/MoviesContainer.js
src/index.js

Added routes for MoviesContainer which will be the homepage
also added Login route as well but commented it out for the moment

Added route for homepage of movies

---

src/Containers/App/App.js
src/actions/index.js
src/index.js
src/reducers/index.js
src/reducers/movies.js

**This PR:**
Adds fetch data for movies to global redux state.
**Where to look:**
Look through the Reducers and Action files.

Initial fetch

---

src/Containers/App/App.js
src/Containers/Login/Login.js
src/actions/index.js
src/index.js
src/reducers/index.js
src/reducers/user.js
src/utils/apiCalls.js

This PR:
Adds user post functionality, and sends it to the store.

Add get user info post data to the store

---

package-lock.json
package.json
src/Containers/App/App.test.js
src/Containers/Movie/Movie.js
src/Containers/MoviesContainer/MoviesContainer.js
src/Containers/MoviesContainer/MoviesContainer.scss
src/Containers/MoviesContainer/MoviesContainer.test.js
src/Containers/MoviesContainer/__snapshots__/MoviesContainer.test.js.snap
src/Containers/MoviesDisplay/MoviesDisplay.js
src/Containers/MoviesDisplay/MoviesDisplay.scss
src/Containers/MoviesDisplay/MoviesDisplay.test.js
src/Containers/MoviesDisplay/__snapshots__/MoviesDisplay.test.js.snap
src/reducers/movies.js
src/setupTests.js

- Made sure that movies are being displayed on the homePage
- Added basic style to the movies and its container
- Added snapshot tests to components

Display characters

---

src/Components/Header/Header.js
src/Components/Header/Header.scss
src/Components/NavBar/NavBar.js
src/Components/NavBar/NavBar.scss

When clicking Sign In button in Nav Bar, redirected to Login form.

Add route path from NavBar to Login

---

src/Containers/Login/Login.js
src/reducers/user.js
src/utils/apiCalls.js

Changed the fetch POST request on login to give back a less nested object for easier use.

Fix login fetch bug

---

src/Components/Header/Header.js
src/Components/Header/Header.scss
src/Components/NavBar/NavBar.js
src/Components/NavBar/NavBar.scss
src/Containers/App/App.js
src/Containers/Login/Login.js
src/actions/index.js

Add functionality for Log in / Log out.

Login route

---

src/Containers/Movie/Movie.js
src/Containers/Movie/Movie.scss

- Added style to the movie card

Style movie page

---

public/index.html
src/Components/Header/Header.js
src/Components/Header/Header.scss
src/Components/NavBar/NavBar.js
src/Components/NavBar/NavBar.scss
src/Containers/App/App.scss
src/Containers/Login/Login.js
src/Containers/Login/Login.scss
src/Containers/Movie/Movie.js
src/Containers/Movie/Movie.scss
src/Containers/MoviesContainer/MoviesContainer.scss
src/Containers/MoviesDisplay/MoviesDisplay.js
src/Containers/MoviesDisplay/MoviesDisplay.scss

- Added style to every component
*Let me know what yall think i did change the Movie component a bit*
- Added back button to movies on the Movie component

Restyle page

---

src/Components/Header/Header.scss
src/Components/NavBar/NavBar.js
src/Components/NavBar/NavBar.scss
src/Containers/Login/__snapshots__/Login.test.js.snap
src/Containers/Movie/__snapshots__/Movie.test.js.snap
src/Containers/MoviesDisplay/__snapshots__/MoviesDisplay.test.js.snap

This PR adds a home button functionality so that the user can always get back to the main movies page.

Home button

---

src/Components/NavBar/NavBar.js
src/Containers/Login/Login.js
src/actions/index.js
src/reducers/user.js

This PR adds a logout function onclick of the logout button.  Instead of the previous window.reload, it now navigates back to the movie page, and resets the user in the redux store as an empty object.
Start looking in the NavBar.js file, and also checkout the action and reducer files to see the change in name that better suits its multi-functionality.

Logout func

---

src/Components/Header/Header.test.js
src/Components/Header/__snapshots__/Header.test.js.snap
src/Components/NavBar/NavBar.js
src/Components/NavBar/NavBar.test.js
src/Components/NavBar/__snapshots__/NavBar.test.js.snap
src/Containers/Login/Login.js
src/actions/index.js
src/actions/index.test.js
src/reducers/user.js
src/reducers/user.test.js

This PR adds snapshots and testing structure for Header.test.js and NavBar.test.js.  It also added a test for setUser from mapDispatchToProps within the NavBar.test.js file.
Start looking at those two files, and examine the NavBar.js file for comparison.

Navbar header testing

---

package.json
src/Components/NavBar/NavBar.test.js
src/utils/apiCalls.js
src/utils/apiCalls.test.js

This PR adds testing to the apiCalls file for the fetchUser function.

Api calls testing

---

src/Containers/Movie/Movie.js
src/Containers/MoviesDisplay/MoviesDisplay.js

This PR adds a selector to choose a rating for a movie, as well as adds some styling elements for this.

Movie rating

---

src/Containers/MoviesDisplay/MoviesDisplay.scss

Added background to the movies, as it was hard to tell what belonged to what.  This made it more clear.

Add background color to movies to give context

---

public/index.html
src/Containers/Login/Login.js
src/Containers/Login/Login.scss
src/actions/index.js
src/reducers/error.js
src/reducers/index.js

Error Handling now works for login but
**BUG WITH NAVLINK** 
It does not redirect back to home, if you log userFound before it returns as true it falsies twice which prevents it i think to navlink home properly
I added error and logged in messages so the user is aware if they have or have not logged in

Add error handling

---

src/Containers/Login/Login.js
src/actions/index.js
src/reducers/index.js
src/reducers/userRatings.js
src/utils/apiCalls.js

This PR adds a fetch for the user ratings, and then pushes that up to the redux store.  It also merges conflicts from our two working branches.

User rating fetch

---

src/Containers/Login/Login.js
src/Containers/MoviesDisplay/MoviesDisplay.js
src/actions/index.js
src/reducers/index.js
src/reducers/userRatings.js
src/utils/apiCalls.js

This PR displays the ratings on movies where the user has rated them.
Look at MoviesDisplay.js to see how it is rendered.

Display ratings

---

src/Containers/Login/Login.js
src/Containers/Login/__snapshots__/Login.test.js.snap
src/Containers/Movie/Movie.js
src/Containers/MoviesContainer/__snapshots__/MoviesContainer.test.js.snap
src/Containers/MoviesDisplay/MoviesDisplay.js
src/Containers/MoviesDisplay/__snapshots__/MoviesDisplay.test.js.snap
src/utils/apiCalls.js

This PR adds functionality to setting a rating where once set, the rating will show on the movie show and main movie pages without a refresh.

Repopulate ratings

---

src/Containers/Login/Login.js
src/Containers/Movie/Movie.scss

This PR fixes the bug with login.  Essentially on button press, the user was still logged out, so the logged out process still ran.  This way, it's logged out, then on press changes to logged in in local state, which causes a re-render, which causes the if statement on the redirect conditional to be met, finally sending you to the movie page.

Fix login bug

---

src/Components/Header/Header.js
src/Components/Header/Header.scss
src/Components/NavBar/NavBar.scss
src/Containers/App/App.scss
src/Containers/Login/Login.js
src/Containers/Login/Login.scss
src/Containers/Movie/Movie.js
src/Containers/Movie/Movie.scss
src/Containers/MoviesDisplay/MoviesDisplay.js
src/Containers/MoviesDisplay/MoviesDisplay.scss

This PR adds styling that fixes some of the issues with the movie show page, as well as adding some overall.

Add styling

---

src/Components/Header/__snapshots__/Header.test.js.snap
src/Containers/Login/__snapshots__/Login.test.js.snap
src/Containers/Movie/Movie.js
src/Containers/Movie/Movie.test.js
src/Containers/Movie/__snapshots__/Movie.test.js.snap
src/Containers/MoviesDisplay/MoviesDisplay.test.js
src/Containers/MoviesDisplay/__snapshots__/MoviesDisplay.test.js.snap

This PR adds props to snapshot tests.

Lastday testing

---

src/Components/NavBar/NavBar.test.js
src/Containers/Movie/Movie.js
src/Containers/Movie/Movie.test.js
src/actions/index.test.js
src/reducers/error.test.js
src/reducers/userRatings.test.js
src/utils/mockData.js

Adds map dispatch testing for movie, as well as reducer and action tests

Movie and other tests

---

package.json
src/Components/Header/Header.js
src/Components/NavBar/NavBar.js
src/Containers/App/App.js
src/Containers/Login/Login.js
src/Containers/Movie/Movie.js
src/Containers/Movie/Movie.test.js
src/Containers/MoviesContainer/MoviesContainer.js
src/Containers/MoviesDisplay/MoviesDisplay.js

This PR adds testing for the handlechange in movie.test.js.

Add handlechange movie testing

---

src/utils/apiCalls.js
src/utils/apiCalls.test.js

Add more tests for apiCalls
